Adapted to multiple output directories.

diff --git a/PromptAna/PromptAnalyzer/analysis/merge_multiple b/PromptAna/PromptAnalyzer/analysis/merge_multiple
--- a/PromptAna/PromptAnalyzer/analysis/merge_multiple
+++ b/PromptAna/PromptAnalyzer/analysis/merge_multiple
@@ -1,5 +1,25 @@
 #!/bin/bash
 
+#----------------------------------------------------------------------------------------------------
+
+function PrintUsage()
+{
+	echo "USAGE: merge_multiple <directory>"
+}
+
+#----------------------------------------------------------------------------------------------------
+
+base_dir="$1"
+
+if [ ! -d "$base_dir" ]
+then
+	echo "ERROR: directory \"$base_dir\" does not exist."
+	PrintUsage
+	exit 1
+fi
+
+#----------------------------------------------------------------------------------------------------
+
 function MergeOneRun()
 {
 	local dir="$1"
@@ -44,6 +64,8 @@ function MergeOneDataSet()
 }
 
 #----------------------------------------------------------------------------------------------------
+
+cd "$base_dir"
 
 MergeOneRun "TOTEM2/319176" &
 MergeOneRun "TOTEM2/319256" &
